#!/bin/bash
# embedded options to qsub - start with #PBS # -- our name ---

#PBS -N fba_ibm_vessels

#PBS -q hpc
#PBS -l walltime=4:00:00
#PBS -l vmem=6GB

#PBS -M fba@aqua.dtu.dk
#PBS -m abe
# -- run in the current working (submission) directory --

cd $PBS_O_WORKDIR

