all:
	(cd formats && make -f Makefile.hpc)
	(cd commons && make -f Makefile.hpc)
	(cd simulator && make -f Makefile.hpc)

install:
	(cd formats && make -f Makefile.hpc install)
	(cd commons && make -f Makefile.hpc install)
	(cd simulator && make -f Makefile.hpc install)

clean:
	(cd formats && make -f Makefile.hpc clean)
	(cd commons && make -f Makefile.hpc clean)
	(cd simulator && make -f Makefile.hpc clean)


