#############################################################################
# Makefile for building: displace
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  displace.pro
# Template: subdirs
# Command: C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\bin\qmake.exe -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile displace.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-commons \
		sub-QMapControl \
		sub-qtgui \
		sub-simulator


sub-commons-qmake_all:  FORCE
	@if not exist commons\ mkdir commons\ & if not exist commons\ exit 1
	cd commons\ && $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\commons\commons.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd commons\ && $(MAKE) -f Makefile qmake_all
sub-commons: FORCE
	@if not exist commons\ mkdir commons\ & if not exist commons\ exit 1
	cd commons\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\commons\commons.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-commons-make_first-ordered: FORCE
	@if not exist commons\ mkdir commons\ & if not exist commons\ exit 1
	cd commons\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\commons\commons.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-commons-make_first: FORCE
	@if not exist commons\ mkdir commons\ & if not exist commons\ exit 1
	cd commons\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\commons\commons.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-commons-all-ordered: FORCE
	@if not exist commons\ mkdir commons\ & if not exist commons\ exit 1
	cd commons\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\commons\commons.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-commons-all: FORCE
	@if not exist commons\ mkdir commons\ & if not exist commons\ exit 1
	cd commons\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\commons\commons.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-commons-clean-ordered: FORCE
	@if not exist commons\ mkdir commons\ & if not exist commons\ exit 1
	cd commons\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\commons\commons.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-commons-clean: FORCE
	@if not exist commons\ mkdir commons\ & if not exist commons\ exit 1
	cd commons\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\commons\commons.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-commons-distclean-ordered: FORCE
	@if not exist commons\ mkdir commons\ & if not exist commons\ exit 1
	cd commons\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\commons\commons.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-commons-distclean: FORCE
	@if not exist commons\ mkdir commons\ & if not exist commons\ exit 1
	cd commons\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\commons\commons.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-commons-install_subtargets-ordered: FORCE
	@if not exist commons\ mkdir commons\ & if not exist commons\ exit 1
	cd commons\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\commons\commons.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-commons-install_subtargets: FORCE
	@if not exist commons\ mkdir commons\ & if not exist commons\ exit 1
	cd commons\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\commons\commons.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-commons-uninstall_subtargets-ordered: FORCE
	@if not exist commons\ mkdir commons\ & if not exist commons\ exit 1
	cd commons\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\commons\commons.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-commons-uninstall_subtargets: FORCE
	@if not exist commons\ mkdir commons\ & if not exist commons\ exit 1
	cd commons\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\commons\commons.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-QMapControl-qmake_all: sub-commons-qmake_all FORCE
	@if not exist QMapControl\ mkdir QMapControl\ & if not exist QMapControl\ exit 1
	cd QMapControl\ && $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\QMapControl\QMapControl.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd QMapControl\ && $(MAKE) -f Makefile qmake_all
sub-QMapControl: FORCE
	@if not exist QMapControl\ mkdir QMapControl\ & if not exist QMapControl\ exit 1
	cd QMapControl\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\QMapControl\QMapControl.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-QMapControl-make_first-ordered: sub-commons-make_first-ordered  FORCE
	@if not exist QMapControl\ mkdir QMapControl\ & if not exist QMapControl\ exit 1
	cd QMapControl\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\QMapControl\QMapControl.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-QMapControl-make_first: FORCE
	@if not exist QMapControl\ mkdir QMapControl\ & if not exist QMapControl\ exit 1
	cd QMapControl\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\QMapControl\QMapControl.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-QMapControl-all-ordered: sub-commons-all-ordered  FORCE
	@if not exist QMapControl\ mkdir QMapControl\ & if not exist QMapControl\ exit 1
	cd QMapControl\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\QMapControl\QMapControl.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-QMapControl-all: FORCE
	@if not exist QMapControl\ mkdir QMapControl\ & if not exist QMapControl\ exit 1
	cd QMapControl\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\QMapControl\QMapControl.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-QMapControl-clean-ordered: sub-commons-clean-ordered  FORCE
	@if not exist QMapControl\ mkdir QMapControl\ & if not exist QMapControl\ exit 1
	cd QMapControl\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\QMapControl\QMapControl.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-QMapControl-clean: FORCE
	@if not exist QMapControl\ mkdir QMapControl\ & if not exist QMapControl\ exit 1
	cd QMapControl\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\QMapControl\QMapControl.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-QMapControl-distclean-ordered: sub-commons-distclean-ordered  FORCE
	@if not exist QMapControl\ mkdir QMapControl\ & if not exist QMapControl\ exit 1
	cd QMapControl\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\QMapControl\QMapControl.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-QMapControl-distclean: FORCE
	@if not exist QMapControl\ mkdir QMapControl\ & if not exist QMapControl\ exit 1
	cd QMapControl\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\QMapControl\QMapControl.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-QMapControl-install_subtargets-ordered: sub-commons-install_subtargets-ordered  FORCE
	@if not exist QMapControl\ mkdir QMapControl\ & if not exist QMapControl\ exit 1
	cd QMapControl\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\QMapControl\QMapControl.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-QMapControl-install_subtargets: FORCE
	@if not exist QMapControl\ mkdir QMapControl\ & if not exist QMapControl\ exit 1
	cd QMapControl\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\QMapControl\QMapControl.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-QMapControl-uninstall_subtargets-ordered: sub-commons-uninstall_subtargets-ordered  FORCE
	@if not exist QMapControl\ mkdir QMapControl\ & if not exist QMapControl\ exit 1
	cd QMapControl\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\QMapControl\QMapControl.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-QMapControl-uninstall_subtargets: FORCE
	@if not exist QMapControl\ mkdir QMapControl\ & if not exist QMapControl\ exit 1
	cd QMapControl\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\QMapControl\QMapControl.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-qtgui-qmake_all: sub-QMapControl-qmake_all FORCE
	@if not exist qtgui\ mkdir qtgui\ & if not exist qtgui\ exit 1
	cd qtgui\ && $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\qtgui\qtgui.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd qtgui\ && $(MAKE) -f Makefile qmake_all
sub-qtgui: FORCE
	@if not exist qtgui\ mkdir qtgui\ & if not exist qtgui\ exit 1
	cd qtgui\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\qtgui\qtgui.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-qtgui-make_first-ordered: sub-QMapControl-make_first-ordered  FORCE
	@if not exist qtgui\ mkdir qtgui\ & if not exist qtgui\ exit 1
	cd qtgui\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\qtgui\qtgui.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-qtgui-make_first: FORCE
	@if not exist qtgui\ mkdir qtgui\ & if not exist qtgui\ exit 1
	cd qtgui\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\qtgui\qtgui.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-qtgui-all-ordered: sub-QMapControl-all-ordered  FORCE
	@if not exist qtgui\ mkdir qtgui\ & if not exist qtgui\ exit 1
	cd qtgui\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\qtgui\qtgui.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-qtgui-all: FORCE
	@if not exist qtgui\ mkdir qtgui\ & if not exist qtgui\ exit 1
	cd qtgui\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\qtgui\qtgui.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-qtgui-clean-ordered: sub-QMapControl-clean-ordered  FORCE
	@if not exist qtgui\ mkdir qtgui\ & if not exist qtgui\ exit 1
	cd qtgui\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\qtgui\qtgui.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-qtgui-clean: FORCE
	@if not exist qtgui\ mkdir qtgui\ & if not exist qtgui\ exit 1
	cd qtgui\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\qtgui\qtgui.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-qtgui-distclean-ordered: sub-QMapControl-distclean-ordered  FORCE
	@if not exist qtgui\ mkdir qtgui\ & if not exist qtgui\ exit 1
	cd qtgui\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\qtgui\qtgui.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-qtgui-distclean: FORCE
	@if not exist qtgui\ mkdir qtgui\ & if not exist qtgui\ exit 1
	cd qtgui\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\qtgui\qtgui.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-qtgui-install_subtargets-ordered: sub-QMapControl-install_subtargets-ordered  FORCE
	@if not exist qtgui\ mkdir qtgui\ & if not exist qtgui\ exit 1
	cd qtgui\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\qtgui\qtgui.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-qtgui-install_subtargets: FORCE
	@if not exist qtgui\ mkdir qtgui\ & if not exist qtgui\ exit 1
	cd qtgui\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\qtgui\qtgui.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-qtgui-uninstall_subtargets-ordered: sub-QMapControl-uninstall_subtargets-ordered  FORCE
	@if not exist qtgui\ mkdir qtgui\ & if not exist qtgui\ exit 1
	cd qtgui\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\qtgui\qtgui.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-qtgui-uninstall_subtargets: FORCE
	@if not exist qtgui\ mkdir qtgui\ & if not exist qtgui\ exit 1
	cd qtgui\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\qtgui\qtgui.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-simulator-qmake_all: sub-qtgui-qmake_all FORCE
	@if not exist simulator\ mkdir simulator\ & if not exist simulator\ exit 1
	cd simulator\ && $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\simulator\simulator.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd simulator\ && $(MAKE) -f Makefile qmake_all
sub-simulator: FORCE
	@if not exist simulator\ mkdir simulator\ & if not exist simulator\ exit 1
	cd simulator\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\simulator\simulator.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-simulator-make_first-ordered: sub-qtgui-make_first-ordered  FORCE
	@if not exist simulator\ mkdir simulator\ & if not exist simulator\ exit 1
	cd simulator\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\simulator\simulator.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-simulator-make_first: FORCE
	@if not exist simulator\ mkdir simulator\ & if not exist simulator\ exit 1
	cd simulator\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\simulator\simulator.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-simulator-all-ordered: sub-qtgui-all-ordered  FORCE
	@if not exist simulator\ mkdir simulator\ & if not exist simulator\ exit 1
	cd simulator\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\simulator\simulator.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-simulator-all: FORCE
	@if not exist simulator\ mkdir simulator\ & if not exist simulator\ exit 1
	cd simulator\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\simulator\simulator.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-simulator-clean-ordered: sub-qtgui-clean-ordered  FORCE
	@if not exist simulator\ mkdir simulator\ & if not exist simulator\ exit 1
	cd simulator\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\simulator\simulator.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-simulator-clean: FORCE
	@if not exist simulator\ mkdir simulator\ & if not exist simulator\ exit 1
	cd simulator\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\simulator\simulator.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-simulator-distclean-ordered: sub-qtgui-distclean-ordered  FORCE
	@if not exist simulator\ mkdir simulator\ & if not exist simulator\ exit 1
	cd simulator\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\simulator\simulator.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-simulator-distclean: FORCE
	@if not exist simulator\ mkdir simulator\ & if not exist simulator\ exit 1
	cd simulator\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\simulator\simulator.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-simulator-install_subtargets-ordered: sub-qtgui-install_subtargets-ordered  FORCE
	@if not exist simulator\ mkdir simulator\ & if not exist simulator\ exit 1
	cd simulator\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\simulator\simulator.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-simulator-install_subtargets: FORCE
	@if not exist simulator\ mkdir simulator\ & if not exist simulator\ exit 1
	cd simulator\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\simulator\simulator.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-simulator-uninstall_subtargets-ordered: sub-qtgui-uninstall_subtargets-ordered  FORCE
	@if not exist simulator\ mkdir simulator\ & if not exist simulator\ exit 1
	cd simulator\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\simulator\simulator.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-simulator-uninstall_subtargets: FORCE
	@if not exist simulator\ mkdir simulator\ & if not exist simulator\ exit 1
	cd simulator\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\simulator\simulator.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: displace.pro .qmake.conf C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/win32-g++/qmake.conf C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/features/spec_pre.prf \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/qdevice.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/features/device_config.prf \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/common/shell-win32.conf \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/qconfig.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_axbase.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_axbase_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_axcontainer.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_axcontainer_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_axserver.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_axserver_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_bluetooth.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_bluetooth_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_bootstrap_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_clucene_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_concurrent.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_concurrent_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_core.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_core_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_declarative.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_declarative_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_designer.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_designer_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_designercomponents_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_enginio.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_enginio_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_gui.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_gui_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_help.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_help_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_multimedia.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_multimedia_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_multimediawidgets.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_network.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_network_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_nfc.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_nfc_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_opengl.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_opengl_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_openglextensions.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_openglextensions_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_platformsupport_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_positioning.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_positioning_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_printsupport.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_printsupport_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_qml.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_qml_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_qmltest.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_qmltest_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_quick.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_quick_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_quickparticles_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_quickwidgets.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_script.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_script_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_scripttools.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_scripttools_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_sensors.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_sensors_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_serialport.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_serialport_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_sql.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_sql_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_svg.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_svg_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_testlib.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_testlib_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_uitools.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_uitools_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_webkit.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_webkit_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_webkitwidgets.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_websockets.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_websockets_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_widgets.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_widgets_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_winextras.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_winextras_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_xml.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_xml_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_xmlpatterns.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/features/qt_functions.prf \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/features/qt_config.prf \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/features/win32/qt_config.prf \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/win32-g++/qmake.conf \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/features/spec_post.prf \
		.qmake.conf \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/features/exclusive_builds.prf \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/features/default_pre.prf \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/features/win32/default_pre.prf \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/features/resolve_config.prf \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/features/exclusive_builds_post.prf \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/features/default_post.prf \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/features/qml_debug.prf \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/features/declarative_debug.prf \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/features/win32/rtti.prf \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/features/precompile_header.prf \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/features/warn_on.prf \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/features/win32/windows.prf \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/features/testcase_targets.prf \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/features/exceptions.prf \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/features/yacc.prf \
		C:/Qt/qt-5.3.2-x64-mingw491r1-seh-opengl/qt-5.3.2-x64-mingw491r1-seh-opengl/mkspecs/features/lex.prf \
		displace.pro
	$(QMAKE) -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile displace.pro
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\features\spec_pre.prf:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\qdevice.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\features\device_config.prf:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\common\shell-win32.conf:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\qconfig.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_axbase.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_axbase_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_axcontainer.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_axcontainer_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_axserver.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_axserver_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_bluetooth.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_clucene_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_concurrent.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_core.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_core_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_declarative.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_declarative_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_designer.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_designer_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_designercomponents_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_enginio.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_enginio_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_gui.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_gui_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_help.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_help_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_multimedia.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_network.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_network_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_nfc.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_nfc_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_opengl.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_openglextensions.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_platformsupport_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_positioning.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_positioning_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_qml.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_qml_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_qmltest.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_quick.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_quick_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_script.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_script_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_scripttools.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_scripttools_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_sensors.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_sensors_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_serialport.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_serialport_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_sql.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_sql_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_svg.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_svg_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_uitools.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_uitools_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_webkit.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_webkit_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_webkitwidgets.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_webkitwidgets_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_websockets.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_websockets_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_winextras.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_winextras_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_xml.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_xml_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\features\qt_functions.prf:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\features\qt_config.prf:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\features\win32\qt_config.prf:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\win32-g++\qmake.conf:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\features\spec_post.prf:
.qmake.conf:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\features\exclusive_builds.prf:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\features\default_pre.prf:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\features\win32\default_pre.prf:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\features\resolve_config.prf:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\features\exclusive_builds_post.prf:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\features\default_post.prf:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\features\qml_debug.prf:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\features\declarative_debug.prf:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\features\win32\rtti.prf:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\features\precompile_header.prf:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\features\warn_on.prf:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\features\win32\windows.prf:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\features\testcase_targets.prf:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\features\exceptions.prf:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\features\yacc.prf:
C:\Qt\qt-5.3.2-x64-mingw491r1-seh-opengl\qt-5.3.2-x64-mingw491r1-seh-opengl\mkspecs\features\lex.prf:
displace.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile displace.pro

qmake_all: sub-commons-qmake_all sub-QMapControl-qmake_all sub-qtgui-qmake_all sub-simulator-qmake_all FORCE

make_first: sub-commons-make_first-ordered sub-QMapControl-make_first-ordered sub-qtgui-make_first-ordered sub-simulator-make_first-ordered FORCE
all: sub-commons-all-ordered sub-QMapControl-all-ordered sub-qtgui-all-ordered sub-simulator-all-ordered FORCE
clean: sub-commons-clean-ordered sub-QMapControl-clean-ordered sub-qtgui-clean-ordered sub-simulator-clean-ordered FORCE
distclean: sub-commons-distclean-ordered sub-QMapControl-distclean-ordered sub-qtgui-distclean-ordered sub-simulator-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-commons-install_subtargets-ordered sub-QMapControl-install_subtargets-ordered sub-qtgui-install_subtargets-ordered sub-simulator-install_subtargets-ordered FORCE
uninstall_subtargets: sub-commons-uninstall_subtargets-ordered sub-QMapControl-uninstall_subtargets-ordered sub-qtgui-uninstall_subtargets-ordered sub-simulator-uninstall_subtargets-ordered FORCE

sub-commons-debug_ordered:
	@if not exist commons\ mkdir commons\ & if not exist commons\ exit 1
	cd commons\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\commons\commons.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-QMapControl-debug_ordered: sub-commons-debug_ordered 
	@if not exist QMapControl\ mkdir QMapControl\ & if not exist QMapControl\ exit 1
	cd QMapControl\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\QMapControl\QMapControl.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-qtgui-debug_ordered: sub-QMapControl-debug_ordered 
	@if not exist qtgui\ mkdir qtgui\ & if not exist qtgui\ exit 1
	cd qtgui\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\qtgui\qtgui.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-simulator-debug_ordered: sub-qtgui-debug_ordered 
	@if not exist simulator\ mkdir simulator\ & if not exist simulator\ exit 1
	cd simulator\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\simulator\simulator.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-commons-debug_ordered sub-QMapControl-debug_ordered sub-qtgui-debug_ordered sub-simulator-debug_ordered

sub-commons-release_ordered:
	@if not exist commons\ mkdir commons\ & if not exist commons\ exit 1
	cd commons\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\commons\commons.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile release
sub-QMapControl-release_ordered: sub-commons-release_ordered 
	@if not exist QMapControl\ mkdir QMapControl\ & if not exist QMapControl\ exit 1
	cd QMapControl\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\QMapControl\QMapControl.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile release
sub-qtgui-release_ordered: sub-QMapControl-release_ordered 
	@if not exist qtgui\ mkdir qtgui\ & if not exist qtgui\ exit 1
	cd qtgui\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\qtgui\qtgui.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile release
sub-simulator-release_ordered: sub-qtgui-release_ordered 
	@if not exist simulator\ mkdir simulator\ & if not exist simulator\ exit 1
	cd simulator\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\simulator\simulator.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile release
release: sub-commons-release_ordered sub-QMapControl-release_ordered sub-qtgui-release_ordered sub-simulator-release_ordered

sub-commons-check_ordered:
	@if not exist commons\ mkdir commons\ & if not exist commons\ exit 1
	cd commons\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\commons\commons.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-QMapControl-check_ordered: sub-commons-check_ordered 
	@if not exist QMapControl\ mkdir QMapControl\ & if not exist QMapControl\ exit 1
	cd QMapControl\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\QMapControl\QMapControl.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-qtgui-check_ordered: sub-QMapControl-check_ordered 
	@if not exist qtgui\ mkdir qtgui\ & if not exist qtgui\ exit 1
	cd qtgui\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\qtgui\qtgui.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-simulator-check_ordered: sub-qtgui-check_ordered 
	@if not exist simulator\ mkdir simulator\ & if not exist simulator\ exit 1
	cd simulator\ && ( if not exist Makefile $(QMAKE) C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\simulator\simulator.pro -spec win32-g++ CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
check: sub-commons-check_ordered sub-QMapControl-check_ordered sub-qtgui-check_ordered sub-simulator-check_ordered
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

